// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseLayout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css\"><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css\"><link rel=\"stylesheet\" href=\"/static/css/app.css\"><style type=\"text/tailwindcss\">\n\t\t\t\t::-webkit-scrollbar { width: 6px; height: 6px; }\n\t\t\t\t::-webkit-scrollbar-track { background: transparent; }\n\t\t\t\t::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 3px; }\n\t\t\t\t::-webkit-scrollbar-thumb:hover { background: #94a3b8; }\n\t\t\t\t@theme {\n\t\t\t\t\t--color-bg: #0D1117;\n\t\t\t\t\t--color-bg-muted: #161B22;\n\t\t\t\t\t--color-elevated: #1C2128;\n\t\t\t\t\t--color-border: #8B949E;\n\t\t\t\t\t--color-border-muted: #30363D;\n\n\t\t\t\t\t--color-bg-text: #E6EDF3;\n\t\t\t\t\t--color-bg-muted: #8B949E;\n\n\t\t\t\t\t--color-text: #E6EDF3;\n\t\t\t\t\t--color-muted: #8B949E;\n\n\t\t\t\t\t--color-primary: #6366F1;\n\t\t\t\t\t--color-success: #3FB950;\n\t\t\t\t\t--color-danger: #F85149;\n\t\t\t\t\t--color-warning: #D29922;\n\n\t\t\t\t\t--color-primary-text: #FFFFFF;\n\t\t\t\t\t--color-success-text: #FFFFFF;\n\t\t\t\t\t--color-danger-text: #FFFFFF;\n\t\t\t\t\t--color-warning-text: #FFFFFF;\n\n\t\t\t\t}\n\n\t\t\t</style></head><body class=\"bg-bg\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js\" integrity=\"sha384-H5SrcfygHmAuTDZphMHqBJLc3FhssKjG7w/CeCpFReSfwBWDTKpkzPP8c+cLsK+V\" crossorigin=\"anonymous\"></script><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script><script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
